routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Models\Category;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();
Route::prefix('/roles')
    ->name('roles.')
    ->middleware(['auth'])
    ->group(function() {
    Route::controller(RoleController::class)
        ->group(function() {
        Route::get('/', 'index')
            ->name('index')
            ->middleware('check.permission:role-view');
        Route::get('/show/{id}', 'show')
            ->name('show')
            ->middleware('check.permission:role-show');
        Route::get('/create', 'create')
            ->name('create')
            ->middleware('check.permission:role-create');
        Route::post('/create', 'store')
            ->name('store')
            ->middleware('check.permission:role-store');
        Route::get('/edit/{id}', 'edit')
            ->name('edit')
            ->middleware('check.permission:role-edit');
        Route::put('/{role}', 'update')
            ->name('update')
            ->middleware('check.permission:role-update');
        Route::delete('/{id}', 'destroy')
            ->name('delete')
            ->middleware('check.permission:role-delete');
    });
});

Route::prefix('/users')
    ->name('users.')
    ->middleware('auth')
    ->group(function() {
    Route::controller(UserController::class)
        ->group(function() {
        Route::get('/', 'index')
            ->name('index')
            ->middleware('check.permission:user-view');
        Route::get('/show/{id}', 'show')
            ->name('show')
            ->middleware('check.permission:user-show');
        Route::get('/create', 'create')
            ->name('create')
            ->middleware('check.permission:user-create');
        Route::post('/create', 'store')
            ->name('store')
            ->middleware('check.permission:user-store');
        Route::get('/edit/{id}', 'edit')
            ->name('edit')
            ->middleware('check.permission:user-edit');
        Route::put('/{id}', 'update')
            ->name('update')
            ->middleware('check.permission:user-update');
        Route::delete('/{id}', 'destroy')
            ->name('delete')
            ->middleware('check.permission:user-delete');
    });
});

Route::prefix('/categories')
    ->name('categories.')
    ->middleware('auth')
    ->group(function() {
    Route::controller(CategoryController::class)
        ->group(function() {
        Route::get('/', 'index')
            ->name('index')
            ->middleware('check.permission:category-view');
        Route::get('/show/{id}', 'show')
            ->name('show')
            ->middleware('check.permission:category-show');
        Route::get('/create', 'create')
            ->name('create')
            ->middleware('check.permission:category-create');
        Route::post('/create', 'store')
            ->name('store')
            ->middleware('check.permission:category-store');
        Route::get('/edit/{id}', 'edit')
            ->name('edit')
            ->middleware('check.permission:category-edit');
        Route::put('/{id}', 'update')
            ->name('update')
            ->middleware('check.permission:category-update');
        Route::delete('/{id}', 'destroy')
            ->name('delete')
            ->middleware('check.permission:category-delete');
    });
});


Route::prefix('/products')
    ->name('products.')
    ->middleware('auth')
    ->group(function() {
    Route::controller(ProductController::class)
        ->group(function() {
        Route::get('/', 'index')
            ->name('index')
            ->middleware('check.permission:product-view');
        Route::get('/list', 'list')
            ->name('list')
            ->middleware('check.permission:product-view');
        Route::get('/show/{id}', 'show')
            ->name('show')
            ->middleware('check.permission:product-show');
        Route::get('/create', 'create')
            ->name('create')
            ->middleware('check.permission:product-create');
        Route::post('/create', 'store')
            ->name('store')
            ->middleware('check.permission:product-store');
        Route::get('/edit/{id}', 'edit')
            ->name('edit')
            ->middleware('check.permission:product-edit');
        Route::put('/{id}', 'update')
            ->name('update')
            ->middleware('check.permission:product-update');
        Route::delete('/{id}', 'destroy')
            ->name('delete')
            ->middleware('check.permission:product-delete');
    });
});


Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])
    ->name('dashboard')

    ->middleware('auth');
Route::redirect('/', '/dashboard');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = [
        'parent_id',
        'name'
    ];

    public function parents()
    {
        return $this->belongsTo(Category::class, 'parent_id', 'id');
    }

    public function childrens()
    {
        return $this->hasMany(Category::class, 'parent_id', 'id');
    }

    public function products()
    {
        return $this->belongsToMany(Category::class);
    }


    public function scopeWithName($query, $name)
    {
        return $name ? $query->where('name', 'like', '%' . $name . '%') : null;
    }

    public function scopeWithParentCategory($query, $parentCategoryId)
    {
        return $parentCategoryId ? $query->where('parent_id', $parentCategoryId) : null;
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Category\CreateCategoryRequest;
use App\Http\Requests\Category\EditCategoryRequest;
use App\Models\Category;
use App\Services\CategoryService;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    protected $categoryService;

    public function __construct(CategoryService $categoryService)
    {
        $this->categoryService = $categoryService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\View
     */
    public function index(Request $request)
    {
        $categories = $this->categoryService->search($request);
        return view('categories.index', [
            'categories' => $categories,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCategoryRequest $request)
    {
        $this->categoryService->create($request);
        return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = $this->categoryService->findOrFail($id);
        $childrens = $this->categoryService->getCategoriesByParent($id);
        return view('categories.show', [
            'category' => $category,
            'childrens' => $childrens
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->categoryService->findOrFail($id);
        return view('categories.edit', [
            'category' => $category
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EditCategoryRequest $request, $id)
    {
        $this->categoryService->update($request, $id);
        return redirect()->route('categories.index')->with('message', 'Update category successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->categoryService->delete($id);
        return redirect()->route('categories.index');
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="content-page mx-2">
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box">
                            <h4 class="page-title">Create Category</h4>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <form action="{{ route('categories.store') }}" method="post" enctype="multipart/form-data">
                        <div class="col-xl-12">
                            @csrf
                            <div class="mb-3">
                                <label for="projectname" class="form-label">Name</label>
                                <input type="text" name="name" class="form-control" placeholder="Enter Category Name" value="{{ old('name') }}"}}>
                            </div>
                            @error('name')
                            <div class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show"
                                 role="alert">
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                                <strong>Error - </strong> {{ $message }}
                            </div>
                            @enderror
                            <div class="mb-3">
                                <label for="projectname" class="form-label">Parent Category</label>
                                <select class="form-control select2" data-toggle="select2" name="parent_id">
                                    <option value="">Select</option>
                                    <optgroup>
                                        @foreach($parentCategories as $category)
                                            <option @selected(old('parent_id') == $category->id) value="{{ $category->id }}">{{ $category->name }}</option>
                                        @endforeach
                                    </optgroup>
                                </select>
                            </div>
                            @error('parent_id')
                            <div class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show"
                                 category="alert">
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                                <strong>Error - </strong> {{ $message }}
                            </div>
                            @enderror
                        <!-- Date View -->
                        <div class="text-center mt-3">
                            <button class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script src="{{ asset('admin/js/category.js') }}" defer></script>
    <script src="{{ asset('admin/js/handleUploadImage.js') }}" defer></script>

@endpush

resources/views/categories/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="content-page mx-2">
        <div class="content">
            <div class="container-fluid">
                <div class="row d-flex align-items-center">
                    <div class="col-6">
                        <div class="page-title-box">
                            <h4 class="page-title">Edit</h4>
                        </div>
                    </div>
                    <div class="col-6 text-end">
                            <form action="{{ route('categories.delete', $category->id) }}" method="post">
                                @csrf
                                @method('delete')
                                <button class="mt-1 btn btn-danger"><i
                                        class="mdi mdi-delete"></i></button>
                            </form>
                    </div>
                </div>
                <div class="row">
                    <form action="{{ route('categories.update', $category) }}" method="post" enctype="multipart/form-data">
                        <div class="col-xl-12">
                            @csrf
                            @method('put')
                            <div class="mb-3">
                                <label for="projectname" class="form-label">Name</label>
                                <input type="text" name="name" class="form-control" placeholder="Enter Category Name" value="{{ $category->name }}">
                            </div>
                            @error('name')
                            <div class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show"
                                 role="alert">
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                                <strong>Error - </strong> {{ $message }}
                            </div>
                            @enderror
                            @if(!$category->childrens()->exists())
                            <div class="mb-3">
                                <label for="projectname" class="form-label">Parent Category</label>
                                <select class="form-control select2" data-toggle="select2" name="parent_id">
                                    <option value="">Select</option>
                                    <optgroup>
                                        @foreach($parentCategories as $parentCategory)
                                            <option {{ $parentCategory->id == $category->parent_id ? 'selected' : ''}} value="{{ $parentCategory->id }}">{{ $parentCategory->name }}</option>
                                        @endforeach
                                    </optgroup>
                                </select>
                            </div>
                            @endif
                            @error('parent_id')
                            <div class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show"
                                 category="alert">
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                                <strong>Error - </strong> {{ $message }}
                            </div>
                            @enderror
                        <!-- Date View -->
                        <div class="text-center mt-3">
                            <button class="btn btn-primary">Update</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script src="{{ asset('admin/js/category.js') }}" defer></script>
    <script src="{{ asset('admin/js/handleUploadImage.js') }}" defer></script>

@endpush

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')
    @if(Session::has('message'))
        <p class="alert alert-info">{{ Session('message') }}</p>
    @endif
    <div class="content">
        <!-- Start Content-->
        <div class="container-fluid">
            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">
                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
                                <li class="breadcrumb-item"><a href="{{ route('categories.index') }}">Category</a></li>
                                <li class="breadcrumb-item active">Category List</li>
                            </ol>
                        </div>
                        <h4 class="page-title">Category</h4>
                    </div>
                </div>
            </div>
            <!-- end page title -->
            @hasPermission('category-create')
            <div class="row mb-2">
                <div class="col-sm-2">
                    <a href="{{ route('categories.create') }}" class="btn btn-success btn-rounded mb-3"><i
                            class="mdi mdi-plus"></i>Create</a>
                </div>
                <div class=" col-sm-8 app-search dropdown d-none d-lg-block">
                    <form method="GET">
                        <div class="d-flex">
                            <input value="{{ request()->name }}" name="name" type="text"
                                   class="form-control mx-1 dropdown-toggle" placeholder="Name..." id="top-search" autocomplete="off" style="padding-left: 10px; background-color: #fff; border: 1px solid #e7ebf0;">
                            <select class="form-control mx-1 select2" data-toggle="select2" name="parent_id">
                                <option value="">Select</option>
                                <optgroup>
                                    @foreach($parentCategories as $parentCategory)
                                        <option {{ request()->parent_id == $parentCategory->id ? 'selected' : '' }} value="{{ $parentCategory->id }}">{{ $parentCategory->name }}</option>
                                    @endforeach
                                </optgroup>
                            </select>
                            <button class="input-group-text btn-primary" type="submit">Search</button>
                        </div>
                    </form>

                </div>
            </div>
            @endhasPermission
            <!-- start row-->
            <div class="container" style="margin-top:30px;">
                <div class="row">
                    @forelse($categories as $category)
                        <ul id="tree2" class="col-sm-2 card mx-1 p-2">
                            <li class="list-unstyled"><a href="{{ route('categories.edit', $category->id) }}" class=""><i class="uil-book"></i>{{ $category->name }}</a>
                                @foreach($category->childrens()->get() as $child)
                                <ul>
                                    <li><a class="text-info" href="{{ route('categories.edit', $child->id) }}">{{ $child->name }}</a></li>
                                </ul>
                                @endforeach
                            </li>
                        </ul>
                    @empty
                        <tbody class="">
                        <td colspan="8"><h1 class="">No matching categories found</h1></td>
                        </tbody>
                    @endforelse
                </div>
            </div>
        </div>
        {{ $categories->appends(request()->all())->links() }}
    </div> <!-- container -->
@endsection
@push('js')
    <script src="{{ asset('admin/js/category.js')}}" defer></script>
@endpush

resources/views/categories/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="content-page mx-2">
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box">
                            <h4 class="page-title">Show</h4>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xl-12">
                        <div class="mb-3">
                            <label for="projectname" class="form-label">Name</label>
                            <input disabled type="text" name="name" class="form-control"
                                   placeholder="Enter Category Name"
                                   value="{{ $category->name }}">
                        </div>
                        @if(!$category->childrens()->exists())
                            <div class="mb-3">
                                <label for="projectname" class="form-label">Parent Category</label>
                                <input disabled type="text" name="name" class="form-control"
                                       placeholder="Enter Category Name"
                                       value="{{ $category->parents->name ?? "" }}">
                            </div>
                        @endif
                    </div>
                </div>
                @if($category->childrens()->exists())
                    <div class="row">
                        <div class="col-sm-12">
                            <table
                                class="table table-centered table-striped dt-responsive nowrap w-100 dataTable no-footer dtr-inline"
                                id="products-datatable" role="grid" aria-describedby="products-datatable_info"
                                style="width: 1554px;">
                                <thead>
                                <tr role="row">
                                    <th tabindex="0" aria-controls="products-datatable" rowspan="1" colspan="1"
                                        aria-label="Customer: activate to sort column ascending">
                                        Childrens Categories
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    @foreach($childrens as $child)
                                        <td class="table-category">
                                            <a href="{{ route('categories.show', $child->id) }}"
                                               class="text-body fw-semibold">{{ $child->name }}</a>
                                        </td>
                                </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <!-- end row-->
                    {{ $childrens->links() }}
{{--                                    {{ $category->childrens()->appends(request()->all())->links() }}--}}
            </div> <!-- container -->
        </div>
    </div>
    @endif
@endsection
@push('js')
    <script src="{{ asset('admin/js/category.js') }}" defer></script>
    <script src="{{ asset('admin/js/handleUploadImage.js') }}" defer></script>

@endpush