routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Models\Category;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();
Route::prefix('/roles')
    ->name('roles.')
    ->middleware(['auth'])
    ->group(function() {
    Route::controller(RoleController::class)
        ->group(function() {
        Route::get('/', 'index')
            ->name('index')
            ->middleware('check.permission:role-view');
        Route::get('/show/{id}', 'show')
            ->name('show')
            ->middleware('check.permission:role-show');
        Route::get('/create', 'create')
            ->name('create')
            ->middleware('check.permission:role-create');
        Route::post('/create', 'store')
            ->name('store')
            ->middleware('check.permission:role-store');
        Route::get('/edit/{id}', 'edit')
            ->name('edit')
            ->middleware('check.permission:role-edit');
        Route::put('/{role}', 'update')
            ->name('update')
            ->middleware('check.permission:role-update');
        Route::delete('/{id}', 'destroy')
            ->name('delete')
            ->middleware('check.permission:role-delete');
    });
});

Route::prefix('/users')
    ->name('users.')
    ->middleware('auth')
    ->group(function() {
    Route::controller(UserController::class)
        ->group(function() {
        Route::get('/', 'index')
            ->name('index')
            ->middleware('check.permission:user-view');
        Route::get('/show/{id}', 'show')
            ->name('show')
            ->middleware('check.permission:user-show');
        Route::get('/create', 'create')
            ->name('create')
            ->middleware('check.permission:user-create');
        Route::post('/create', 'store')
            ->name('store')
            ->middleware('check.permission:user-store');
        Route::get('/edit/{id}', 'edit')
            ->name('edit')
            ->middleware('check.permission:user-edit');
        Route::put('/{id}', 'update')
            ->name('update')
            ->middleware('check.permission:user-update');
        Route::delete('/{id}', 'destroy')
            ->name('delete')
            ->middleware('check.permission:user-delete');
    });
});

Route::prefix('/categories')
    ->name('categories.')
    ->middleware('auth')
    ->group(function() {
    Route::controller(CategoryController::class)
        ->group(function() {
        Route::get('/', 'index')
            ->name('index')
            ->middleware('check.permission:category-view');
        Route::get('/show/{id}', 'show')
            ->name('show')
            ->middleware('check.permission:category-show');
        Route::get('/create', 'create')
            ->name('create')
            ->middleware('check.permission:category-create');
        Route::post('/create', 'store')
            ->name('store')
            ->middleware('check.permission:category-store');
        Route::get('/edit/{id}', 'edit')
            ->name('edit')
            ->middleware('check.permission:category-edit');
        Route::put('/{id}', 'update')
            ->name('update')
            ->middleware('check.permission:category-update');
        Route::delete('/{id}', 'destroy')
            ->name('delete')
            ->middleware('check.permission:category-delete');
    });
});


Route::prefix('/products')
    ->name('products.')
    ->middleware('auth')
    ->group(function() {
    Route::controller(ProductController::class)
        ->group(function() {
        Route::get('/', 'index')
            ->name('index')
            ->middleware('check.permission:product-view');
        Route::get('/list', 'list')
            ->name('list')
            ->middleware('check.permission:product-view');
        Route::get('/show/{id}', 'show')
            ->name('show')
            ->middleware('check.permission:product-show');
        Route::get('/create', 'create')
            ->name('create')
            ->middleware('check.permission:product-create');
        Route::post('/create', 'store')
            ->name('store')
            ->middleware('check.permission:product-store');
        Route::get('/edit/{id}', 'edit')
            ->name('edit')
            ->middleware('check.permission:product-edit');
        Route::put('/{id}', 'update')
            ->name('update')
            ->middleware('check.permission:product-update');
        Route::delete('/{id}', 'destroy')
            ->name('delete')
            ->middleware('check.permission:product-delete');
    });
});


Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])
    ->name('dashboard')

    ->middleware('auth');
Route::redirect('/', '/dashboard');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use League\CommonMark\Extension\Attributes\Node\Attributes;

class Product extends Model
{
    use HasFactory;

    const STORAGE_PATH = '/uploads/';

    protected $fillable = [
        'name',
        'price',
        'description',
        'image'
    ];

    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }

    public function syncCategory($categoryId)
    {
        return $this->categories()->sync($categoryId);
    }

    public function detachCategory(array $categoryId = [])
    {
        return $this->categories()->detach($categoryId);
    }

    public function scopeWithName($query, $name)
    {
        return $name ? $query->where('name', 'like', '%' . $name . '%') : null;
    }

    public function scopeWithCategory($query, $categoryId)
    {
//        return $categoryId ? $query->whereHas( 'categories', function ($query) use ($categoryId) {
//            return $query->where('category_id', $categoryId);
//        }) : null;
        return $categoryId ? $query->whereHas('categories', fn($category) => $category->where('category_id', $categoryId)) : null;
    }


    public function scopeWithMinPrice($query, $minPrice)
    {
        return $minPrice ? $query->where('price', '>', $minPrice) : null;
    }

    public function scopeWithMaxPrice($query, $maxPrice)
    {
        return $maxPrice ? $query->where('price', '<', $maxPrice) : null;
    }

    protected function image(): Attribute
    {
        return Attribute::make(
            get: fn ($value) => asset( self::STORAGE_PATH . $value)
        );

    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Product\CreateProductRequest;
use App\Http\Requests\Product\EditProductRequest;
use App\Http\Resources\ProductResource;
use App\Services\ProductService;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    protected $productService;

    public function __construct(ProductService $productService)
    {
        $this->productService = $productService;
    }

    public function index()
    {
        return view('products.index');
    }

    public function list(Request $request)
    {
        $products = $this->productService->search($request);
        return view('products.list', [
            'products' => $products,
        ])->render();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(CreateProductRequest $request)
    {
        $product = $this->productService->create($request);
        $productResource = new ProductResource($product);
        return $this->sentSuccesResponse($productResource, 'Product created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = $this->productService->findOrFail($id);
        $productResource = new ProductResource($product);
        return $this->sentSuccesResponse($productResource);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return string
     */
    public function edit($id)
    {
        $product = $this->productService->findOrFail($id);
        $productResource = new ProductResource($product);
        return $this->sentSuccesResponse($productResource);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(EditProductRequest $request, $id)
    {
        $product = $this->productService->update($request, $id);
        $productResource = new ProductResource($product);
        return $this->sentSuccesResponse($productResource, 'Update Product Successfuly');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = $this->productService->delete($id);
        $productResource = new ProductResource($product);
        return $this->sentSuccesResponse($productResource, 'Delete Product Successfuly');
    }
}

resources/views/products/create.blade.php
<div class="modal fade" id="modal-create-product" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document" style="max-width: 800px;">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title font-weight-normal text-dark" id="exampleModalLabel">
                    Create New Product</h5>
                <button type="button" class="btn-close text-dark" data-bs-dismiss="modal"
                        aria-label="Close">
                </button>
            </div>
            <div class="modal-body">
                <form id="form-create-product" data-action="{{ route('products.store')  }}"
                      enctype="multipart/form-data">
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-3">
                        @csrf
                        <div class="form-group custom-form-group-create">
                            <strong class="form-check">Name: </strong>
                            <div class="form-check input-group input-group-dynamic info-horizontal">
                                <input type="text" name="name" id="name" class="form-control shadow-none"
                                       style="outline: none">
                            </div>
                            <div style="display: none"
                                 class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show  mx-3 my-1 name_error errors"></div>
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-12 mt-3">
                        <div class="form-group custom-form-group-create">
                            <strong class="form-check">Price: </strong>
                            <div class="form-check input-group input-group-dynamic info-horizontal">
                                <input type="text" name="price" id="price" class="form-control shadow-none"
                                       style="outline: none">
                            </div>
                            <div style="display: none"
                                 class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show  mx-3 my-1 price_error errors"></div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-3">
                        <div class="form-group custom-form-group-create">
                            <strong class="form-check">Description: </strong>
                            <div class="form-check input-group input-group-dynamic info-horizontal">
                                <textarea type="text" name="description" id="description" class="form-control shadow-none description-abc"
                                       style="outline: none"></textarea>
                            </div>
                            <div style="display: none"
                                 class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show  mx-3 my-1 description_error errors"></div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-3">
                        <div class="form-group custom-form-group-create">
                            <strong class="form-check">Image: </strong>

                            <div class="form-check input-group input-group-dynamic info-horizontal">
                                <input class="form-control image-input" name="image" type="file" id="image">
                            </div>
                            <div style="display: none"
                                 class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show  mx-3 my-1 image_error errors"></div>
                        </div>
                        <!-- Preview -->
                        <div class="dropzone-previews mx-3 mt-3 position-relative" id="file-previews"
                             style="display: none">
                            <button type="button" class="btn-close close-image position-absolute"
                                    style="top: 2%; left: 0.5%;" aria-label="Close"></button>
                            <img class="rounded bg-light image-data img-thumbnail .img-fluid"
                                 style="max-width: 30%; height: auto;"/>
                        </div>
                    </div>
                    <div class="form-group mx-3">
                        <label for="" class="text-lg text-bold text-dark mt-2 font-14 my-3">Category</label>
                        <div class="h-25 d-flex flex-wrap justify-content-sm-between">
                            @foreach($categories as $category)
                                <div class="form-check mb-2 w-25">
                                    <input type="checkbox" class="form-check-input" name="category_ids[]" id="{{ $category->id  }}" value="{{ $category->id }}">
                                    <label class="form-check-label" for="{{ $category->id  }}">{{ $category->name }}</label>
                                </div>
                            @endforeach
                        </div>
                        <div style="display: none"
                             class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show my-1 category_ids_error errors"></div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn bg-gradient-secondary btn-warning" data-bs-dismiss="modal">
                    Close
                </button>
                <button type="button" class="btn bg-gradient-primary btn-store-product btn-success">Add</button>
            </div>
        </div>
    </div>
</div>

resources/views/products/edit.blade.php
<div class="modal fade" id="modal-edit-product" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document" style="max-width: 800px;">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title font-weight-normal text-dark" id="exampleModalLabel">
                    Update New Product</h5>
                <button type="button" class="btn-close text-dark" data-bs-dismiss="modal"
                        aria-label="Close">
                </button>
            </div>
            <div class="modal-body">
                <form id="form-edit-product" data-action=""
                      enctype="multipart/form-data">
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-3">
                        @csrf
                        <div class="form-group custom-form-group-create">
                            <strong class="form-check">Name: </strong>
                            <div class="form-check input-group input-group-dynamic info-horizontal">
                                <input type="text" name="name" id="name_edit" class="form-control form-edit shadow-none"
                                       style="outline: none">
                            </div>
                            <div style="display: none"
                                 class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show  mx-3 my-1 name_error errors"></div>
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-12 mt-3">
                        <div class="form-group custom-form-group-create">
                            <strong class="form-check">Price: </strong>
                            <div class="form-check input-group input-group-dynamic info-horizontal">
                                <input type="text" name="price" id="price_edit" class="form-control form-edit shadow-none"
                                       style="outline: none">
                            </div>
                            <div style="display: none"
                                 class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show  mx-3 my-1 price_error errors"></div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-3">
                        <div class="form-group custom-form-group-create">
                            <strong class="form-check">Description: </strong>
                            <div class="form-check input-group input-group-dynamic info-horizontal">
                                <textarea type="text" name="description" id="description_edit" class="form-control form-edit shadow-none description-abc"
                                       style="outline: none"></textarea>
                            </div>
                            <div style="display: none"
                                 class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show  mx-3 my-1 description_error errors"></div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-3">
                        <div class="form-group custom-form-group-create">
                            <strong class="form-check">Image: </strong>

                            <div class="form-check input-group input-group-dynamic info-horizontal">
                                <input class="form-control form-edit image-input" name="image" type="file" id="image">
                            </div>
                            <div style="display: none"
                                 class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show  mx-3 my-1 image_error errors"></div>
                        </div>
                        <!-- Preview -->
                        <div class="dropzone-previews mx-3 mt-3 position-relative" id="file-previews"
                             >
                            <button type="button" class="btn-close close-image position-absolute"
                                    style="top: 2%; left: 0.5%;" aria-label="Close"></button>
                            <img class="image_edit rounded bg-light image-data img-thumbnail .img-fluid"
                                 style="max-width: 30%; height: auto;"/>
                        </div>
                    </div>
                    <div class="form-group mx-3">
                        <label for="" class="text-lg text-bold text-dark mt-2 font-14 my-3">Category</label>
                        <div class="h-25 d-flex flex-wrap justify-content-sm-between">
                            @foreach($categories as $category)
                                <div class="form-check mb-2 w-25">
                                    <input type="checkbox" class="form-check-edit form-edit" name="category_ids[]" id="{{ $category->id  }}" value="{{ $category->id }}">
                                    <label class="form-check-label" for="{{ $category->id  }}">{{ $category->name }}</label>
                                </div>
                            @endforeach
                        </div>
                        <div style="display: none"
                             class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show my-1 category_ids_error errors"></div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn bg-gradient-secondary btn-warning" data-bs-dismiss="modal">
                    Close
                </button>
                <button type="button" class="btn bg-gradient-primary btn-update-product btn-success">Update</button>
            </div>
        </div>
    </div>
</div>

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
    @if(Session::has('message'))
        <p class="alert alert-info">{{ Session('message') }}</p>
    @endif
    <div class="content">
        <!-- Start Content-->
        <div class="container-fluid">
            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">
                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
                                <li class="breadcrumb-item"><a href="{{ route('products.index') }}">Product</a></li>
                                <li class="breadcrumb-item active">Product List</li>
                            </ol>
                        </div>
                        <h4 class="page-title">Product</h4>
                    </div>
                </div>
            </div>
            <!-- end page title -->
            @hasPermission('product-create')
            <div class="row mb-2">
                <div class="col-sm-2">
                    <button type="button" data-bs-toggle="modal" data-bs-target="#modal-create-product"
                            class="btn btn-success btn-rounded mb-3 btn-create"><i
                            class="mdi mdi-plus" data-toggle="modal"></i>Create
                    </button>
                </div>
                <div class="col-sm-8 app-search dropdown d-none d-lg-block">
                    <form method="GET" class="form-search">
                        <div class="input-group">
                            <input value="{{ request()->name }}" name="name" type="text" autocomplete="off"
                                   class="form-control search-field" placeholder="Search..." id="top-search" style="padding-left: 10px; background-color: #fff; border: 1px solid #e7ebf0;">
                        </div>
                        <div class=" form-group mt-2 w-100" id="search-dropdown">
                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="dropdown-header noti-title">
                                        <h6 class="text-overflow text-uppercase">Category</h6>
                                        <select class="form-control select2" data-toggle="select2" name="category" style="padding-left: 10px; background-color: #fff; border: 1px solid #e7ebf0;">
                                            <option value="">Select</option>
                                            <optgroup>
                                                @foreach($categories as $category)
                                                    <option
                                                        {{ request()->category == $category->id ? 'selected' : '' }} value="{{ $category->id }}">{{ $category->name }}</option>
                                                @endforeach
                                            </optgroup>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="dropdown-header noti-title">
                                        <h6 class="text-overflow text-uppercase">Min Price</h6>
                                        <input value="" name="min_price" type="text" autocomplete="off"
                                               class="form-control search-field" placeholder="Min Price"
                                               id="top-search" style="padding-left: 10px; background-color: #fff; border: 1px solid #e7ebf0;">
                                    </div>

                                </div>
                                <div class="col-sm-4">
                                    <div class="dropdown-header noti-title">
                                        <h6 class="text-overflow text-uppercase">Max Price</h6>
                                        <input value="" name="max_price" type="text" autocomplete="off"
                                               class="form-control search-field" placeholder="Max Price"
                                               id="top-search" style="padding-left: 10px; background-color: #fff; border: 1px solid #e7ebf0;">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            @endhasPermission
            <!-- start row-->
            @include('products.create')
            @include('products.edit')
            <div id="list" data-action="{{ route('products.list') }}">
            </div>
            {{--Edit Product--}}
            <!-- end row-->
        </div> <!-- container -->
    </div>
@endsection
@push('js')
    <script src="{{ asset('admin/js/handleUploadImage.js')}}" defer></script>
    <script src="{{ asset('admin/js/product.js')}}" defer></script>
@endpush

resources/views/products/list.blade.php
<div class="row">
    <div class="col-sm-12">
        <table
            class="table table-centered table-striped dt-responsive nowrap w-100 dataTable no-footer dtr-inline"
            id="products-datatable" role="grid" aria-describedby="products-datatable_info"
            style="width: 1554px;">
            <thead>
            <tr role="row">
                <th tabindex="0" aria-controls="products-datatable" rowspan="1" colspan="1"
                    aria-label="Customer: activate to sort column ascending" style="min-width: 200px;">
                    {{ucfirst('name')}}
                </th>
                <th tabindex="0" aria-controls="products-datatable" rowspan="1" colspan="1"

                    aria-label="Phone: activate to sort column ascending">{{ucfirst('price')}}
                </th>
                <th class="sorting_disabled" rowspan="1" colspan="1"
                    aria-label="Action"> {{ucfirst('category')}}
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                @forelse($products as $product)
                    <td class="table-user">
                        <img src="{{ $product->image }}" alt="table-user"
                             class="me-2 rounded-circle">
                        <a data-action="{{ route('products.show', $product->id) }}"
                           class="btn-show text-title text-body fw-semibold" data-toggle="modal" data-bs-toggle="modal"
                           data-bs-target="#modal-edit-product">{{ $product->name }}</a>
                    </td>
                    <td>
                        ${{ number_format($product->price, 2) }}
                    </td>
                    <td>
                        {{--                                    {{ $product->gender }}--}}
                        @foreach($product->categories()->get() as $category)
                            {{--                                        <option {{ request()->category_id == $category->id ? 'selected' : '' }} value="{{ $category->id }}"></option>--}}
                            <span class="badge bg-success">{{ $category->name }}</span>
                        @endforeach
                    </td>
                    <td class="d-flex justify-content-sm-evenly align-items-center">
                        <div class="justify-content-center d-flex">
                            @hasPermission('product-edit')
                            <button data-action="{{ route('products.edit', $product->id) }}"
                                    class="btn btn-warning mx-1 btn-edit" data-toggle="modal" data-bs-toggle="modal"
                                    data-bs-target="#modal-edit-product"><i class="mdi mdi-wrench"></i>
                            </button>
                            @endhasPermission
                            @hasPermission('product-delete')
                            <button data-action="{{ route('products.delete', $product->id) }}"
                                    class="btn btn-danger btn-delete"><i
                                    class="mdi mdi-window-close"></i>
                            </button>
                            @endhasPermission
                        </div>
                    </td>
            </tr>
            @empty
                <tbody class="">
                <td colspan="8" class="text-center"><h1 class="">No matching products found</h1></td>
                </tbody>
            @endforelse
                </tbody>
        </table>
    </div>
</div>
{{ $products->appends(request()->all())->links() }}