routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Models\Category;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();
Route::prefix('/roles')
    ->name('roles.')
    ->middleware(['auth'])
    ->group(function() {
    Route::controller(RoleController::class)
        ->group(function() {
        Route::get('/', 'index')
            ->name('index')
            ->middleware('check.permission:role-view');
        Route::get('/show/{id}', 'show')
            ->name('show')
            ->middleware('check.permission:role-show');
        Route::get('/create', 'create')
            ->name('create')
            ->middleware('check.permission:role-create');
        Route::post('/create', 'store')
            ->name('store')
            ->middleware('check.permission:role-store');
        Route::get('/edit/{id}', 'edit')
            ->name('edit')
            ->middleware('check.permission:role-edit');
        Route::put('/{role}', 'update')
            ->name('update')
            ->middleware('check.permission:role-update');
        Route::delete('/{id}', 'destroy')
            ->name('delete')
            ->middleware('check.permission:role-delete');
    });
});

Route::prefix('/users')
    ->name('users.')
    ->middleware('auth')
    ->group(function() {
    Route::controller(UserController::class)
        ->group(function() {
        Route::get('/', 'index')
            ->name('index')
            ->middleware('check.permission:user-view');
        Route::get('/show/{id}', 'show')
            ->name('show')
            ->middleware('check.permission:user-show');
        Route::get('/create', 'create')
            ->name('create')
            ->middleware('check.permission:user-create');
        Route::post('/create', 'store')
            ->name('store')
            ->middleware('check.permission:user-store');
        Route::get('/edit/{id}', 'edit')
            ->name('edit')
            ->middleware('check.permission:user-edit');
        Route::put('/{id}', 'update')
            ->name('update')
            ->middleware('check.permission:user-update');
        Route::delete('/{id}', 'destroy')
            ->name('delete')
            ->middleware('check.permission:user-delete');
    });
});

Route::prefix('/categories')
    ->name('categories.')
    ->middleware('auth')
    ->group(function() {
    Route::controller(CategoryController::class)
        ->group(function() {
        Route::get('/', 'index')
            ->name('index')
            ->middleware('check.permission:category-view');
        Route::get('/show/{id}', 'show')
            ->name('show')
            ->middleware('check.permission:category-show');
        Route::get('/create', 'create')
            ->name('create')
            ->middleware('check.permission:category-create');
        Route::post('/create', 'store')
            ->name('store')
            ->middleware('check.permission:category-store');
        Route::get('/edit/{id}', 'edit')
            ->name('edit')
            ->middleware('check.permission:category-edit');
        Route::put('/{id}', 'update')
            ->name('update')
            ->middleware('check.permission:category-update');
        Route::delete('/{id}', 'destroy')
            ->name('delete')
            ->middleware('check.permission:category-delete');
    });
});


Route::prefix('/products')
    ->name('products.')
    ->middleware('auth')
    ->group(function() {
    Route::controller(ProductController::class)
        ->group(function() {
        Route::get('/', 'index')
            ->name('index')
            ->middleware('check.permission:product-view');
        Route::get('/list', 'list')
            ->name('list')
            ->middleware('check.permission:product-view');
        Route::get('/show/{id}', 'show')
            ->name('show')
            ->middleware('check.permission:product-show');
        Route::get('/create', 'create')
            ->name('create')
            ->middleware('check.permission:product-create');
        Route::post('/create', 'store')
            ->name('store')
            ->middleware('check.permission:product-store');
        Route::get('/edit/{id}', 'edit')
            ->name('edit')
            ->middleware('check.permission:product-edit');
        Route::put('/{id}', 'update')
            ->name('update')
            ->middleware('check.permission:product-update');
        Route::delete('/{id}', 'destroy')
            ->name('delete')
            ->middleware('check.permission:product-delete');
    });
});


Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])
    ->name('dashboard')

    ->middleware('auth');
Route::redirect('/', '/dashboard');

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;
//    protected $with = ['permissions'];
    const STORAGE_PATH = '/uploads/';

    protected $fillable = [
        'name',
        'display_name',
        'image'
    ];

    public function users()
    {
        return $this->belongsToMany(User::class);
    }

    public function permissions()
    {
        return $this->belongsToMany(Permission::class);
    }

    public function scopeWithName($query, $name)
    {
        return $query->where('display_name', 'like', '%' . $name . '%');
    }

    public function hasPermission($permission)
    {
        return $this->permissions->contains('name', $permission);
    }

    public function syncPermissions($permissionId)
    {
        return $this->permissions()->sync($permissionId);
    }

    public function detachPermissions(array $permissionId = [])
    {
        return $this->permissions()->detach($permissionId);
    }

    protected function image(): Attribute
    {
        return Attribute::make(
            get: fn($value) => asset(self::STORAGE_PATH . $value)
        );

    }

}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Role\CreateRoleRequest;
use App\Http\Requests\Role\EditRoleRequest;
use App\Models\Role;
use App\Services\PermissionService;
use App\Services\RoleService;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\View;

class RoleController extends Controller
{

    protected $roleService;

    public function __construct(RoleService $roleService)
    {
        $this->roleService = $roleService;
    }

    public function index(Request $request)
    {
        $roles = $this->roleService->search($request);
        return view('roles.index', [
            'roles' => $roles,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
//        $permissions = $this->permissionService->getAllPermissions();
        return view('roles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return Response
     */
    public function store(CreateRoleRequest $request)
    {
        $this->roleService->create($request);
        return redirect()->route('roles.index')->with('message', 'Role created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $role = $this->roleService->findOrFail($id);
        return view('roles.show', [
            'role' => $role
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $role = $this->roleService->findOrFail($id);
        return view('roles.edit', [
            'role' => $role
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(EditRoleRequest $request, Role $role)
    {
        $this->roleService->update($request, $role->id);
        return redirect()->route('roles.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        $this->roleService->delete($id);
        return redirect()->route('roles.index');
    }
}

resources/views/roles/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="content-page mx-2">
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box">
                            <h4 class="page-title">Create Role</h4>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <form action="{{ route('roles.store') }}" method="post" enctype="multipart/form-data">
                        <div class="col-xl-12">
                            @csrf
                            <div class="mb-3">
                                <label for="projectname" class="form-label">Name</label>
                                <input type="text" name="name" class="form-control" placeholder="Enter role name">
                            </div>
                            @error('name')
                            <div class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show"
                                 role="alert">
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                                <strong>Error - </strong> {{ $message }}
                            </div>
                            @enderror
                        <!-- Date View -->
                            <div class="mb-3">
                                <label for="project-budget" class="form-label">Display Name</label>
                                <input type="text" name="display_name" class="form-control"
                                       placeholder="Enter display name">
                            </div>
                            @error('display_name')
                            <div class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show"
                                 role="alert">
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                                <strong>Error - </strong> {{ $message }}
                            </div>
                            @enderror
                            <div class="mb-3">
                                <label for="example-fileinput" class="form-label">Image</label>
                                <input type="file" name="image" class="form-control image-input">
                            </div>

                            @error('image')
                            <div class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show"
                                 role="alert">
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                                <strong>Error - </strong> {{ $message }}
                            </div>
                        @enderror
                            <!-- Preview -->
                            <div class="dropzone-previews mt-3 position-relative" id="file-previews" style="display: none">
                                <button type="button" class="btn-close position-absolute close-image" style="top: 2%; left: 0.5%;" aria-label="Close"></button>
                                <img class="rounded bg-light image-data img-thumbnail .img-fluid" style="max-width: 30%; height: auto;"/>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input check-all-permission select-all" type="checkbox"
                                       id="checkAll">
                                <label class="form-label" for="checkAll">ALL</label>
                                <div class="row">
                                    @foreach($permissionGroups as $group => $permissions)
                                        <div class="col checkbox-wrapper">
                                            <input
                                                class="select-group select-all-{{strtolower($group)}}"
                                                type="checkbox" id="{{ $group }}">
                                            <label class="form-label"
                                                   for="{{ $group }}"><b>{{ ucfirst( $group )}}</b></label>
                                            @foreach($permissions as $permission)
                                                <div class="card-text">
                                                    <div class="form-check">
                                                        <input
                                                            class="select-item select-item-{{strtolower($group)}}"
                                                            type="checkbox" id="{{ $permission->id }}"
                                                            name="permission_names[]"
                                                            value="{{ $permission->id }}">
                                                        <label class="form-check-label"
                                                               for="{{ $permission->id }}">
                                                            {{ $permission->display_name }}
                                                        </label>
                                                    </div>
                                                </div>
                                            @endforeach
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                        </div> <!-- end col-->
                        <div class="text-center mt-3">
                            <button class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script src="{{ asset('admin/js/role.js') }}" defer></script>
    <script src="{{ asset('admin/js/handleUploadImage.js') }}" defer></script>

@endpush

resources/views/roles/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="content-page mx-2">
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box">
                            <h4 class="page-title">Edit Role</h4>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xl-12">
                        <form action="{{ route('roles.update', $role) }}" method="post"
                              enctype="multipart/form-data">
                            @csrf
                            @method('put')
                            <div class="mb-3">
                                <label for="projectname" class="form-label">Name</label>
                                <input type="text" name="name" class="form-control" placeholder="Enter role name"
                                       value="{{ $role->name }}">
                            </div>
                            @error('name')
                            <div class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show"
                                 role="alert">
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                                <strong>Error - </strong> {{ $message }}
                            </div>
                            @enderror
                        <!-- Date View -->
                            <div class="mb-3">
                                <label for="project-budget" class="form-label">Display Name</label>
                                <input type="text" name="display_name" class="form-control"
                                       placeholder="Enter display name" value="{{ $role->display_name }}">
                            </div>
                            @error('display_name')
                            <div class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show"
                                 role="alert">
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                                <strong>Error - </strong> {{ $message }}
                            </div>
                            @enderror
                            <div class="mb-3">
                                <label for="example-fileinput" class="form-label">Image</label>
                                <input type="file" name="image" class="form-control image-input" alt="{{ $role->image }}">
                            </div>
                            @error('image')
                            <div class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show"
                                 role="alert">
                                <button type="button" class="btn-close " data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                                <strong>Error - </strong> {{ $message }}
                            </div>
                            @enderror
                            <!-- Preview -->
                            <div class="dropzone-previews mt-3 position-relative" id="file-previews">
                                <button type="button" class="btn-close position-absolute close-image" style="top: 3%; left: 0.5%;" aria-label="Close"></button>
                                <img src="{{ $role->image }}" class="rounded bg-light image-data img-thumbnail" style="max-width: 30%; height: auto;"/>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input check-all-permission select-all" type="checkbox"
                                       id="checkAll">
                                <label class="form-label" for="checkAll">ALL</label>
                                <div class="row">
                                    @foreach($permissionGroups as $group => $permissions)
                                        <div class="col checkbox-wrapper">
                                            <input
                                                class="select-group"
                                                type="checkbox" id="{{ $group }}">
                                            <label class="form-label"
                                                   for="{{ $group }}"><b>{{ ucfirst( $group )}}</b></label>
                                            @foreach($permissions as $permission)
                                                <div class="card-text">
                                                    <div class="form-check">
                                                        <input
                                                            {{ $role->permissions->contains($permission->id) ? 'checked' : '' }}
                                                            class="select-item"
                                                            type="checkbox" id="{{ $permission->id }} "
                                                            name="permission_names[]"
                                                            value="{{ $permission->id }}">
                                                        <label class="form-check-label"
                                                               for="{{ $permission->id }}">
                                                            {{ $permission->display_name }}
                                                        </label>
                                                    </div>
                                                </div>
                                            @endforeach
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                            <div class="text-center">
                                <button class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div> <!-- end col-->
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <script src="{{ asset('admin/js/role.js') }}" defer></script>
    <script src="{{ asset('admin/js/handleUploadImage.js') }}" defer></script>
@endpush

resources/views/roles/index.blade.php
@extends('layouts.app')

@section('content')
    @if (Session::has('message'))
        <p class="alert alert-info">{{ Session('message') }}</p>
    @endif
    <div class="content">
        <!-- Start Content-->
        <div class="container-fluid">
            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">
                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
                                <li class="breadcrumb-item"><a href="{{ route('roles.index') }}">Role</a></li>
                                <li class="breadcrumb-item active">Role List</li>
                            </ol>
                        </div>
                        <h4 class="page-title">Role</h4>
                    </div>
                </div>
            </div>
            <!-- end page title -->
            <div class="row mb-2">
                <div class="col-sm-4">
                    @hasPermission('role-create')
                    <a href="{{ route('roles.create') }}" class="btn btn-success btn-rounded mb-3"><i
                            class="mdi mdi-plus"></i>Create</a>
                    @endhasPermission
                </div>

                <div class=" col-sm-4 app-search dropdown d-none d-lg-block">
                    <form method="GET">
                        <div class="input-group">
                            <input value="{{ request()->name }}" name="name" type="text"
                                class="form-control dropdown-toggle" placeholder="Search..." id="top-search">
                            <span class="mdi mdi-magnify search-icon"></span>
                            <button class="input-group-text btn-primary" type="submit">Search</button>
                        </div>
                    </form>
                </div>
                <div class="col-sm-4">
                    <form class="w-25 float-end" method="GET">
                        <select class="form-control mx-1 select2 select-paginate" data-toggle="select2" name="paginate_number">
                            <option value="">Select</option>
                            <optgroup>
                                @for($i = 4; $i <= 50; $i+=4)
                                    <option
                                        {{ request()->paginate_number == $i ? 'selected' : '' }} value="{{ $i }}">{{ $i }}</option>
                                @endfor
                            </optgroup>
                        </select>
                        <button class="input-group-text btn-primary btn-change-paginate d-none" type="submit">Submit</button>
                    </form>
                </div>
            </div>
            <!-- start row-->
            <div class="row">
                @forelse ($roles as $role)
                    <div class="col-md-6 col-xxl-3">
                        <!-- project card -->
                        <div class="card d-block">
                            <!-- project-thumbnail -->
                            <img class="card-img-top" src="{{ $role->image ?? asset('uploads/' . 'default.jpg') }}"
                                alt="project image cap">
                            <div class="card-body position-relative">
                                <div class="progress progress-sm">
                                    <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0"
                                        aria-valuemax="100"
                                        style="width: {{ $role->name == 'super-admin' ? '100' : ($role->permissions_count / $permissionCount) * 100 }}%;">
                                    </div>
                                </div>
                                <h4 class="mt-2">
                                    <a href="{{ route('roles.show', $role->id) }}"
                                        class="text-title">{{ $role->display_name }}</a>
                                </h4>
                                <!-- project detail-->
                                <p class="mb-3">
                                    <span class="pe-2 text-nowrap">
                                        <i class="mdi mdi-format-list-bulleted-type"></i>
                                        <b>{{ $role->name == 'super-admin' ? 'Full' : $role->permissions_count }}</b>
                                        Permission
                                    </span>
                                    <span class="text-nowrap">
                                        <i class="mdi mdi-comment-multiple-outline"></i>
                                        <b>{{ $role->users_count }} People</b>
                                    </span>
                                </p>
                                <div class="justify-content-center d-flex mt-3">
                                    @hasPermission('role-edit')
                                    <form action="{{ route('roles.edit', $role->id) }}" class="mx-1">
                                        <button type="submit" class="btn btn-warning"><i class="mdi mdi-wrench"></i>
                                        </button>
                                    </form>
                                    @endhasPermission
                                    @hideInMyRole($role->name)
                                    @hasPermission('role-delete')
                                    <form action="{{ route('roles.delete', $role->id) }}" method="post">
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="btn btn-danger"><i class="mdi mdi-window-close"></i>
                                        </button>
                                    </form>
                                    @endhasPermission
                                    @endhideInMyRole
                                </div>
                            </div> <!-- end card-body-->
                        </div> <!-- end card-->
                    </div> <!-- end col -->
                @empty
                    <div class="mt-5 d-flex justify-content-center align-items-center">
                        <h1 colspan="8" class="dataTables_empty">No matching roles found</h1>
                    </div>
                @endforelse
            </div>
            <!-- end row-->
            {{-- {{ $roles->links() }} --}}
            {{ $roles->appends(request()->all())->links() }}
        </div> <!-- container -->
    </div>
@endsection
@push('js')
    <script src="{{ asset('admin/js/role.js') }}" defer></script>
@endpush